package com.mindtree.testscripts;

import java.io.File;
import java.io.IOException;

import org.openqa.selenium.Cookie;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.ITestResult;
import org.testng.annotations.AfterClass;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;

import io.github.bonigarcia.wdm.WebDriverManager;

public class FindMyRoomLoginLocalTest {

	static ThreadLocal<RemoteWebDriver> driver = new ThreadLocal<>();
	static ExtentReports extent;
	static ThreadLocal<ExtentTest> logger = new ThreadLocal<>();

	final static String CHROME_DRIVER_PATH = "C:\\Users\\poc-playground\\Documents\\chrome driver\\chromedriver.exe";

	final static String APP_URL = "http://poc-docker.eastus.cloudapp.azure.com:8076/#/";

	@BeforeClass
	public void beforeClass() {
		WebDriverManager.chromedriver().setup();
		System.setProperty("webdriver.chrome.driver", CHROME_DRIVER_PATH);

		extent = new ExtentReports(System.getProperty("user.dir") + "/test-output/ExtentReport.html", true);
		extent.addSystemInfo("Reports Generated By: ", "Akshata Vernekar");
		extent.loadConfig(new File(System.getProperty("user.dir") + "\\extent-config.xml"));
	}

	@Test
	public void registerUserTest() throws InterruptedException, IOException {

		ChromeOptions options = new ChromeOptions();
		options.addArguments("--start-maximized");
		driver.set(new ChromeDriver(options));

		logger.set(extent.startTest("Register User", "This Test is to register a user to find my room application"));
		driver.get().get(APP_URL);
		logger.get().log(LogStatus.PASS, "Successfully launched Find My Room URL");
		captureScreenshot(driver.get(), logger.get());

		driver.get().findElementByXPath("//div[@id='navbarSupportedContent']/ul[2]/li/a").click();
		logger.get().log(LogStatus.PASS, "Successfully clicked on Login Button");
		captureScreenshot(driver.get(), logger.get());

		driver.get().findElementByXPath("//a[contains(text(),'Register')]").click();
		logger.get().log(LogStatus.PASS, "Successfully clicked on Register Button");
		captureScreenshot(driver.get(), logger.get());

		driver.get().findElementByXPath("//div[@id='signupform']/div/div/div[2]/div/form/div/div[3]/div/label").click();
		logger.get().log(LogStatus.PASS, "Successfully selected Partner option");
		captureScreenshot(driver.get(), logger.get());

		driver.get().findElementByXPath("//input[@id='fName']").sendKeys("Admin");
		logger.get().log(LogStatus.PASS, "Successfully entered first name");
		captureScreenshot(driver.get(), logger.get());

		driver.get().findElementByXPath("//input[@id='uEmail']").sendKeys("admin@frm.com");
		logger.get().log(LogStatus.PASS, "Successfully entered email id");
		captureScreenshot(driver.get(), logger.get());

		driver.get().findElementByXPath("//input[@id='uPassword']").sendKeys("Welcome@123");
		logger.get().log(LogStatus.PASS, "Successfully entered password");
		captureScreenshot(driver.get(), logger.get());

		driver.get().findElementByXPath("//input[@id='uConfirm']").sendKeys("Welcome@123");
		logger.get().log(LogStatus.PASS, "Successfully entered confirm password");
		captureScreenshot(driver.get(), logger.get());

		driver.get().findElementByXPath("//input[@id='uPhone']").sendKeys("9876543210");
		logger.get().log(LogStatus.PASS, "Successfully entered phone number");
		captureScreenshot(driver.get(), logger.get());

		driver.get().findElementByXPath("//input[@id='uCity']").sendKeys("Bangalore");
		logger.get().log(LogStatus.PASS, "Successfully entered city");
		captureScreenshot(driver.get(), logger.get());

		driver.get().findElementByXPath("//input[@id='uStreet']").sendKeys("str");
		logger.get().log(LogStatus.PASS, "Successfully entered street");
		captureScreenshot(driver.get(), logger.get());

		driver.get().findElementByXPath("//input[@id='uPostal']").sendKeys("560001");
		logger.get().log(LogStatus.PASS, "Successfully entered postal code");
		captureScreenshot(driver.get(), logger.get());

		driver.get().findElementByXPath("(//button[@type='submit'])[3]").click();
		logger.get().log(LogStatus.PASS, "Successfully registered the user");
		captureScreenshot(driver.get(), logger.get());

	}

	@Test
	public void loginUserTest() throws IOException, InterruptedException {

		ChromeOptions options = new ChromeOptions();
		options.addArguments("--start-maximized");
		driver.set(new ChromeDriver(options));

		driver.get().manage().window().maximize();

		logger.set(extent.startTest("Login User", "This Test is to login a user to find my room application"));

		driver.get().get(APP_URL);
		logger.get().log(LogStatus.PASS, "Successfully launched Find My Room URL");
		captureScreenshot(driver.get(), logger.get());

		driver.get().findElementByXPath("//div[@id='navbarSupportedContent']/ul[2]/li/a").click();
		logger.get().log(LogStatus.PASS, "Successfully clicked on Login Button");
		captureScreenshot(driver.get(), logger.get());

		driver.get().findElementByXPath("//input[@id='loginformEmail']").sendKeys("admin@frm.com");
		logger.get().log(LogStatus.PASS, "Successfully entered login email id");
		captureScreenshot(driver.get(), logger.get());

		driver.get().findElementByXPath("//input[@id='loginformPassword']").sendKeys("Welcome@123");
		logger.get().log(LogStatus.PASS, "Successfully entered login password");
		captureScreenshot(driver.get(), logger.get());

		driver.get().findElementByXPath("//button[@type='submit']").click();
		logger.get().log(LogStatus.PASS, "Successfully clicked on SignIn Button");
		captureScreenshot(driver.get(), logger.get());

		driver.get().findElementByXPath("//*[@id='navbarSupportedContent']/ul[2]/li[2]/a").click();
		logger.get().log(LogStatus.PASS, "Successfully clicked on user profile button");
		captureScreenshot(driver.get(), logger.get());

		driver.get().findElementByXPath("//*[@id='navbarSupportedContent']/ul[2]/li[2]/div/a[1]").click();
		logger.get().log(LogStatus.PASS, "Successfully clicked on logout button");
		captureScreenshot(driver.get(), logger.get());

	}

	@AfterMethod
	public void afterMethod(ITestResult result) throws IOException, InterruptedException {
		if (result.getStatus() == ITestResult.FAILURE) {
			Cookie cookie = new Cookie("zaleniumTestPassed", "false");
			driver.get().manage().addCookie(cookie);

			captureScreenshot(driver.get(), logger.get());
			logger.get().log(LogStatus.FAIL, "Test Case Failed is " + result.getName());
			logger.get().log(LogStatus.FAIL, "Test Case Failed is " + result.getThrowable());

		} else if (result.getStatus() == ITestResult.SKIP) {
			logger.get().log(LogStatus.SKIP, "Test Case Skipped is " + result.getName());
		} else {
			Cookie cookie = new Cookie("zaleniumTestPassed", "true");
			driver.get().manage().addCookie(cookie);

		}
		extent.endTest(logger.get());

		driver.get().quit();

	}

	@AfterClass
	public void afterclass() {
		extent.flush();
	}

	public synchronized static void captureScreenshot(RemoteWebDriver driver, ExtentTest logger)
			throws IOException, InterruptedException {
		String base64 = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BASE64);
		logger.log(LogStatus.INFO, "Snapshot below: " + logger.addBase64ScreenShot("data:image/png;base64," + base64));
	}

}
